spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**,/auth/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**

        - id: interaction-service
          uri: lb://INTERACTION-SERVICE
          predicates:
            - Path=/api/interactions/**
            -
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20